export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'fr', label: 'Français' },
  { code: 'mfe', label: 'Kreol Morisien' },
]

const fr = {
  'Dashboard':'Tableau de bord','My Goals':'Mes objectifs','AI Coach':'Coach IA','Transactions':'Transactions','Create Goal':'Créer un objectif','Logout':'Déconnexion',
  'Good afternoon, Aisha':'Bonjour, Aisha','Your financial picture and goals are connected across every screen.':'Votre situation financière et vos objectifs sont liés sur chaque écran.',
  'Financial planning':'Planification financière','Build your financial picture.':'Construisez votre situation financière.','Add your income and expenses so GoalPath can calculate your safe saving capacity and guide your goals.':'Ajoutez vos revenus et dépenses afin que GoalPath calcule votre capacité d’épargne sûre et vous guide.','Get started':'Commencer',
  'Monthly salary':'Salaire mensuel','Monthly expenses':'Dépenses mensuelles','Active goals':'Objectifs actifs','Review finances':'Voir les finances','Edit salary, expenses and view recent transactions.':'Modifiez le salaire, les dépenses et consultez les transactions récentes.','Open overview':'Ouvrir le résumé','Review goals':'Voir les objectifs','See saved goals or analyse a new one.':'Consultez vos objectifs ou analysez-en un nouveau.','Open goals':'Ouvrir les objectifs','Reset demo data':'Réinitialiser les données',
  'FINANCIAL INPUT':'DONNÉES FINANCIÈRES','Add your financial data':'Ajoutez vos données financières','Choose one method. You can review extracted values before they are saved.':'Choisissez une méthode. Vous pourrez vérifier les valeurs avant de les enregistrer.','Upload document':'Téléverser un document','Payslip or statement':'Fiche de paie ou relevé','Voice input':'Saisie vocale','Describe your finances':'Décrivez vos finances','Manual entry':'Saisie manuelle','Type the amounts':'Saisissez les montants','Upload a financial document':'Téléverser un document financier','Select a PDF or image. This demo displays the existing sample values; backend extraction can replace it later.':'Sélectionnez un PDF ou une image. Cette démo affiche les valeurs d’exemple.','Choose a file':'Choisir un fichier','Use the microphone button to simulate a voice entry in this standalone version.':'Utilisez le microphone pour simuler une saisie vocale.','Listening…':'Écoute…','Start recording':'Commencer l’enregistrement','Transcript':'Transcription','Enter the values manually':'Saisissez les valeurs manuellement','Click the editable fields under “Enter your values” and type your own monthly salary and expenses.':'Cliquez sur les champs modifiables et saisissez votre salaire et vos dépenses mensuels.','Enter your values':'Saisissez vos valeurs','Review values':'Vérifier les valeurs','Analyse my finances':'Analyser mes finances','Enter a valid monthly salary and expense amount.':'Saisissez un salaire et des dépenses mensuels valides.',
  'ANALYSIS COMPLETE':'ANALYSE TERMINÉE','Your financial picture is ready':'Votre situation financière est prête','The reviewed values are now available throughout GoalPath.':'Les valeurs vérifiées sont maintenant disponibles dans GoalPath.','Data added successfully':'Données ajoutées avec succès','Source:':'Source :','Safe saving capacity':'Capacité d’épargne sûre','What this means':'Ce que cela signifie','Review financial overview':'Voir le résumé financier','Continue to goals':'Continuer vers les objectifs',
  'MY GOALS':'MES OBJECTIFS','Your financial goals':'Vos objectifs financiers','Create a new goal':'Créer un nouvel objectif','Track your saved goals and see how they fit your financial capacity.':'Suivez vos objectifs et leur compatibilité avec votre capacité financière.','Tell GoalPath what you want to achieve and review the risk profile before adding it.':'Indiquez votre objectif à GoalPath et vérifiez le profil de risque avant de l’ajouter.','New goal':'Nouvel objectif','YOUR PLAN':'VOTRE PLAN','Saved goals':'Objectifs enregistrés','active':'actifs','saved':'épargnés','About':'Environ','months at current capacity':'mois à la capacité actuelle','SAFE':'SÛR','NOT SAFE':'NON SÛR','TIGHT':'SERRÉ',
  'Goal details':'Détails de l’objectif','Goal name':'Nom de l’objectif','Category':'Catégorie','Education':'Éducation','Emergency':'Urgence','Travel':'Voyage','Vehicle':'Véhicule','Home':'Maison','Other':'Autre','Goal amount':'Montant de l’objectif','Target date':'Date cible','Current savings':'Épargne actuelle','Reference link (optional)':'Lien de référence (facultatif)','Describe it your way':'Décrivez-le à votre façon','Type naturally in English, French or Mauritian Creole.':'Écrivez naturellement en anglais, français ou créole mauricien.','Extract goal':'Extraire l’objectif','Analyse goal':'Analyser l’objectif','Analysing...':'Analyse...','The analysis uses the saving capacity from your Financial Overview.':'L’analyse utilise la capacité d’épargne de votre résumé financier.','AI-assisted goal review':'Analyse d’objectif assistée par IA','Your risk profile':'Votre profil de risque','Review this analysis before deciding whether to add the goal.':'Vérifiez cette analyse avant d’ajouter l’objectif.','VERDICT':'VERDICT','Safe to pursue':'Objectif sûr','Possible, but tight':'Possible, mais serré','Not safe today':'Pas sûr actuellement','Monthly amount needed':'Montant mensuel nécessaire','Why GoalPath gave this result':'Pourquoi GoalPath a donné ce résultat','The monthly amount required is compared with the safe saving capacity from your Financial Overview.':'Le montant mensuel requis est comparé à votre capacité d’épargne sûre.','Decline':'Refuser','Add goal':'Ajouter l’objectif',
  'FINANCIAL OVERVIEW':'RÉSUMÉ FINANCIER','Salary, expenses and past transactions':'Salaire, dépenses et transactions passées','Values are shared with Dashboard and Goals. Correct them here without uploading a document again.':'Les valeurs sont partagées avec le tableau de bord et les objectifs. Modifiez-les ici.','Updated from':'Mis à jour depuis','and your manual entries.':'et vos saisies manuelles.','Save':'Enregistrer','Cancel':'Annuler','Edit':'Modifier','Expense summary':'Résumé des dépenses','Past transactions':'Transactions passées','Essential':'Essentiel','Adjustable':'Ajustable','Lifestyle':'Style de vie',
  'Ask about your plan':'Posez des questions sur votre plan','This standalone assistant uses the same saved demo data as the other screens.':'Cet assistant utilise les mêmes données enregistrées que les autres écrans.','Can I afford another goal?':'Puis-je me permettre un autre objectif ?','Send':'Envoyer','You currently have':'Vous avez actuellement','active goals. Your demo safe saving capacity is':'objectifs actifs. Votre capacité d’épargne sûre est de','per month.':'par mois.','For this demo, protect essential expenses first, then compare the monthly amount required by each goal with your safe saving capacity.':'Pour cette démo, protégez d’abord les dépenses essentielles, puis comparez le montant mensuel requis à votre capacité d’épargne sûre.','Supermarket':'Supermarché','Salary':'Salaire','Transport':'Transport','Internet':'Internet','Dining':'Restaurant',
  'WELCOME BACK':'BON RETOUR','Log in to GoalPath':'Se connecter à GoalPath','Demo details are already filled in. Click Log in to continue.':'Les informations de démonstration sont déjà remplies. Cliquez sur Connexion.','Email address':'Adresse e-mail','Password':'Mot de passe','Log in':'Connexion','Plan your goals.':'Planifiez vos objectifs.','Understand your money.':'Comprenez votre argent.','Build a clearer path toward the financial goals that matter to you.':'Construisez un chemin clair vers vos objectifs financiers.','Your financial journey starts here.':'Votre parcours financier commence ici.','Page not found':'Page introuvable','Return to Dashboard':'Retour au tableau de bord','Home':'Accueil','Goals':'Objectifs'
}

const mfe = {
  'Dashboard':'Tablo-de-bor','My Goals':'Mo bann lobzektif','AI Coach':'Coach AI','Transactions':'Tranzaksion','Create Goal':'Kre enn lobzektif','Logout':'Dekonekte',
  'Good afternoon, Aisha':'Bon apre-midi, Aisha','Your financial picture and goals are connected across every screen.':'To sitiasion finansie ek to bann lobzektif konekte lor tou bann paz.','Financial planning':'Planifikasion finansie','Build your financial picture.':'Konstrir to sitiasion finansie.','Add your income and expenses so GoalPath can calculate your safe saving capacity and guide your goals.':'Azout to reveni ek depans pou GoalPath kalkil to kapasite lekonomi an sekirite ek gid to bann lobzektif.','Get started':'Koumanse',
  'Monthly salary':'Saler par mwa','Monthly expenses':'Depans par mwa','Active goals':'Lobzektif aktif','Review finances':'Get finans','Edit salary, expenses and view recent transactions.':'Sanz saler, depans ek get bann dernie tranzaksion.','Open overview':'Ouver rezime','Review goals':'Get bann lobzektif','See saved goals or analyse a new one.':'Get bann lobzektif anrezistre ouswa analiz enn nouvo.','Open goals':'Ouver lobzektif','Reset demo data':'Reinisializ done demo',
  'FINANCIAL INPUT':'ANTRE FINANSIE','Add your financial data':'Azout to bann done finansie','Choose one method. You can review extracted values before they are saved.':'Swazir enn metod. To kapav verifye bann valer avan anrezistre.','Upload document':'Met enn dokiman','Payslip or statement':'Fich lapey ouswa releve','Voice input':'Antre par lavwa','Describe your finances':'Dekrir to finans','Manual entry':'Antre manuel','Type the amounts':'Tap bann montan','Upload a financial document':'Met enn dokiman finansie','Select a PDF or image. This demo displays the existing sample values; backend extraction can replace it later.':'Swazir enn PDF ouswa zimaz. Sa demo-la montre bann valer lexanp.','Choose a file':'Swazir enn fisie','Use the microphone button to simulate a voice entry in this standalone version.':'Servi bouton mikro pou simile enn antre par lavwa.','Listening…':'Pe ekoute…','Start recording':'Koumans anrezistre','Transcript':'Transkripsion','Enter the values manually':'Antre bann valer manuelman','Click the editable fields under “Enter your values” and type your own monthly salary and expenses.':'Klik lor bann ranpli ek tap to saler ek depans par mwa.','Enter your values':'Antre to bann valer','Review values':'Verifye bann valer','Analyse my finances':'Analiz mo finans','Enter a valid monthly salary and expense amount.':'Antre enn saler ek depans valid.',
  'ANALYSIS COMPLETE':'ANALIZ FINI','Your financial picture is ready':'To sitiasion finansie inn pare','The reviewed values are now available throughout GoalPath.':'Bann valer verifye aster disponib partou dan GoalPath.','Data added successfully':'Done inn azoute avek sikse','Source:':'Sours:','Safe saving capacity':'Kapasite lekonomi an sekirite','What this means':'Ki savedir','Review financial overview':'Get rezime finansie','Continue to goals':'Kontinie ver lobzektif',
  'MY GOALS':'MO BANN LOBZEKTIF','Your financial goals':'To bann lobzektif finansie','Create a new goal':'Kre enn nouvo lobzektif','Track your saved goals and see how they fit your financial capacity.':'Swiv to bann lobzektif ek gete kouma zot adapte ar to kapasite finansie.','Tell GoalPath what you want to achieve and review the risk profile before adding it.':'Dir GoalPath seki to anvi realize ek verifye risk avan azoute.','New goal':'Nouvo lobzektif','YOUR PLAN':'TO PLAN','Saved goals':'Lobzektif anrezistre','active':'aktif','saved':'ekonomize','About':'Apepre','months at current capacity':'mwa avek kapasite aktiel','SAFE':'AN SEKIRITE','NOT SAFE':'PA AN SEKIRITE','TIGHT':'SERE',
  'Goal details':'Detay lobzektif','Goal name':'Nom lobzektif','Category':'Kategori','Education':'Ledikasion','Emergency':'Irzans','Travel':'Vwayaz','Vehicle':'Veyikil','Home':'Lakaz','Other':'Lezot','Goal amount':'Montan lobzektif','Target date':'Dat sib','Current savings':'Lekonomi aktiel','Reference link (optional)':'Link referans (opsionel)','Describe it your way':'Dekrir li dan to fason','Type naturally in English, French or Mauritian Creole.':'Ekrir normalman an Angle, Franse ouswa Kreol Morisien.','Extract goal':'Extra lobzektif','Analyse goal':'Analiz lobzektif','Analysing...':'Pe analize...','The analysis uses the saving capacity from your Financial Overview.':'Analiz-la servi kapasite lekonomi depi to rezime finansie.','AI-assisted goal review':'Revizion lobzektif avek AI','Your risk profile':'To profil risk','Review this analysis before deciding whether to add the goal.':'Verifye sa analiz-la avan azout lobzektif.','VERDICT':'REZILTA','Safe to pursue':'An sekirite pou kontinie','Possible, but tight':'Posib, me sere','Not safe today':'Pa an sekirite aster','Monthly amount needed':'Montan neseser par mwa','Why GoalPath gave this result':'Kifer GoalPath inn donn sa rezilta-la','The monthly amount required is compared with the safe saving capacity from your Financial Overview.':'Nou konpar montan neseser par mwa avek kapasite lekonomi an sekirite.','Decline':'Refize','Add goal':'Azout lobzektif',
  'FINANCIAL OVERVIEW':'REZIME FINANSIE','Salary, expenses and past transactions':'Saler, depans ek bann tranzaksion pase','Values are shared with Dashboard and Goals. Correct them here without uploading a document again.':'Bann valer partaze avek tablo-de-bor ek lobzektif. Koriz zot isi.','Updated from':'Miz-a-zour depi','and your manual entries.':'ek to bann antre manuel.','Save':'Anrezistre','Cancel':'Anile','Edit':'Sanze','Expense summary':'Rezime depans','Past transactions':'Tranzaksion pase','Essential':'Esansiel','Adjustable':'Kapav aziste','Lifestyle':'Stil lavi',
  'Ask about your plan':'Demann lor to plan','This standalone assistant uses the same saved demo data as the other screens.':'Sa asistan-la servi mem done demo ki lezot paz.','Can I afford another goal?':'Eski mo kapav permet enn lot lobzektif?','Send':'Avoye','You currently have':'To ena aktielman','active goals. Your demo safe saving capacity is':'lobzektif aktif. To kapasite lekonomi an sekirite se','per month.':'par mwa.','For this demo, protect essential expenses first, then compare the monthly amount required by each goal with your safe saving capacity.':'Pou sa demo-la, protez bann depans esansiel avan, apre konpar montan neseser par mwa avek to kapasite lekonomi.','Supermarket':'Sipermarse','Salary':'Saler','Transport':'Transpor','Internet':'Internet','Dining':'Restoran',
  'WELCOME BACK':'BON RETOUR','Log in to GoalPath':'Konekte lor GoalPath','Demo details are already filled in. Click Log in to continue.':'Bann detay demo fini ranpli. Klik Konekte pou kontinie.','Email address':'Adres imel','Password':'Modpas','Log in':'Konekte','Plan your goals.':'Planifie to bann lobzektif.','Understand your money.':'Konpran to larzan.','Build a clearer path toward the financial goals that matter to you.':'Konstrir enn semin pli kler ver to bann lobzektif finansie.','Your financial journey starts here.':'To parkour finansie koumans isi.','Page not found':'Paz pa trouve','Return to Dashboard':'Retour tablo-de-bor','Home':'Lakaz','Goals':'Lobzektif'
}

const tables = { fr, mfe }

export function translateText(language, value) {
  if (language === 'en' || !value) return value
  const table = tables[language] || {}
  const leading = value.match(/^\s*/)?.[0] || ''
  const trailing = value.match(/\s*$/)?.[0] || ''
  let text = value.trim()
  if (!text) return value
  if (table[text]) return leading + table[text] + trailing
  Object.keys(table).sort((a,b) => b.length-a.length).forEach((key) => { text = text.split(key).join(table[key]) })
  return leading + text + trailing
}
